# Generated by Django 5.1.1 on 2024-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_fullname_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=10)),
            ],
        ),
    ]
