# Generated by Django 4.0.5 on 2022-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('name_company', models.CharField(max_length=50)),
                ('mail_company', models.EmailField(max_length=254)),
                ('phone_company', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Volnteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('name_company', models.CharField(max_length=50)),
                ('mail_company', models.EmailField(max_length=254)),
                ('phone_company', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
