# Generated by Django 4.0.5 on 2022-07-06 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volnteer', '0002_volnteer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='website',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
