# Generated by Django 5.1.1 on 2024-09-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_company'),
        ('volnteer', '0003_charity_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('who_need_help', models.PositiveSmallIntegerField(blank=True, default=(1,))),
                ('type', models.PositiveSmallIntegerField(blank=True, default=(1,), null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='login.company')),
                ('participate', models.ManyToManyField(blank=True, related_name='participate', to='login.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.DeleteModel(
            name='Volnteer',
        ),
    ]
